### ISSUE TITLE
Cann't compile this.

### ISSUE THREAD

**Issue by username1565** [bavlayan/Encrypt-Decrypt-with-OpenSSL---RSA#1]
Cann't compile this.
>g++ -m32 -O3 -o rsa_encrypt_decrypt.exe main.cpp

>**main.cpp:3:25: fatal error: openssl/rsa.h: No such file or directory**

Do you have binaries? Can you put this in releases?

**Comment by username1565** [comment]
Hello, you can test this simple project: https://github.com/username1565/rsaVault
and fix the bugs there or optimize this. For example, decrypt is very slow there...

**Comment by melody26613** [comment]
Hi, which platform do you use for compiling?
I compile it in Debian, and no error occur.
I think you should install openssl library to fix the error, and remember compile with -lcrypto option.
`g++ -m32 -O3 -o rsa_encrypt_decrypt.exe main.cpp -lcrypto`

**Comment by username1565** [comment]
@melody26613
I using MinGW but your string not working,
because I don't have installed openssl there,
and don't know how to install this there.

I think need to include the functions and methods from openssl
to working with RSA without any dependencies.
In this case, this program will be full and portable.
